### ISSUE TITLE
Error fix

### ISSUE THREAD

**Issue by playinteractive** [kuria/error#1]
Hi there,

Sometimes I have to look inside the source-code for see certain errors.

Maybe you can resolve it adding a `redirect` to someplace like:

`domain.com/KuriaError?whatever=`

What do you think?

Cheers

**Comment by shira-374** [comment]
Not sure what you mean. If it's XHR (ajax) requests then most browsers let you preview the HTML error responses.

**Comment by shira-374** [comment]
If you really want to redirect in case of an exception, you can achieve that yourself via the `EXCEPTION` event:

```php
use Kuria\Error\ErrorHandlerEvents;

$errorHandler->on(ErrorHandlerEvents::EXCEPTION, function (\Throwable $exception, bool $debug) {
    if ($debug && !headers_sent() && PHP_SAPI !== 'cli') {
        header(
            'Location: https://example.com/error/?'
                . http_build_query([
                    'message' => $exception->getMessage(),
                    'file' => $exception->getFile(),
                    'line' => $exception->getLine(),
                ])
        );

        exit;    
    } 
});
```
